#!/usr/bin/env bash

#: exec_target = cli

## Update Drupal database to current code branch
##
## Usage: fin drupal-update

# Abort if anything fails
set -euo pipefail

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
yellow=$'\033[1;33m'
NC=$'\033[0m'

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
drush updb -y
drush cim -y
drush uli --browser=0

printf "%s\n" "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
