#!/usr/bin/env bash

#: exec_target = cli

## Run drush in debug mode
##
## Usage: fin drush-debug [command]

set -euo pipefail

PHP_IDE_CONFIG="serverName=patternkit-env.docksal" php "$PROJECT_ROOT"/vendor/drush/drush/drush.php "$1"
