#!/usr/bin/env bash

## Use git-flow to start a new feature branch
##
## Usage: fin feature-start

# Abort if anything fails
set -euo pipefail

#-------------------------- Helper functions --------------------------------

# Console colors
red_bg=$'\033[1;97;41m'
green=$'\033[0;32m'
green_bg=$'\033[1;97;42m'
NC=$'\033[0m'

#-------------------------- Execution --------------------------------

if [[ -z "${1:-}" ]]; then
  printf "%s\n" "${red_bg} ERROR ${NC} Provide a feature name, e.g. \"3107537-module-deps\"."
  exit 1
fi

GIT_USERNAME=$(git config user.name)
USERNAME="$(echo -e "${GIT_USERNAME}" | tr -d '[[:space:]]' | tr '[:upper:]' '[:lower:]')"
if [[ -z "${USERNAME}" ]]; then
  printf "%s\n" "${red_bg} ERROR ${red_bg} Your git username is not configured. Use \"git config user.name\".${NC}"
  exit 1
fi

# Stack initialization
printf "%s\n" "${green_bg} Step 1 ${NC}${green} Stashing current work and checking out a new feature branch...${NC}"
git fetch origin
git add .
git stash save -u "Automatic stash via fin feature-start."
git checkout -f master
git rebase origin/master
git submodule update --rebase --remote
git checkout -b feature/"${USERNAME}"/${1}

# Site initialization
printf "%s\n" "${green_bg} Step 2 ${NC}${green} Updating site...${NC}"
fin drupal-update

printf "%s\n" "${green_bg} DONE! ${NC}${green} Completed all feature branching steps.${NC}"
git status

#-------------------------- END: Execution --------------------------------
