#!/usr/bin/env bash

## Use git-flow to start a new feature branch.
##
## Usage: fin feature-start

# Abort if anything fails
set -euo pipefail

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Stashing current work and checking out a new feature branch...${NC}"
git fetch origin
git stash save -u "Automatic stash via fin feature-start."
git checkout -f master
git rebase origin/master
git submodule update --rebase --remote

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Updating site...${NC}"
fin drupal-update

echo -e "${green_bg} DONE! ${NC}${green} Completed all initialization steps.${NC}"

#-------------------------- END: Execution --------------------------------
