#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -euo pipefail

#-------------------------- Helper functions --------------------------------

# Console colors
green=$'\033[0;32m'
green_bg=$'\033[42m'
NC=$'\033[0m'


#-------------------------- Execution --------------------------------

fin config set --env=local XDEBUG_ENABLED=0
printf "%s\n" "${green_bg} XDEBUG Turned OFF! ${NC} "

# Stack initialization
printf "%s\n" "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
fin project reset -f

# Site initialization
printf "%s\n" "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"
# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
fin init-site

printf "%s\n" "${green_bg} DONE! ${NC}${green} Completed all initialization steps.${NC}"

#-------------------------- END: Execution --------------------------------
