#!/usr/bin/env bash

## Test Patternkit via cli
##
## Usage: fin test-patternkit

#: exec_target = cli

# Abort if anything fails
set -euo pipefail

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
green=$'\033[0;32m'
yellow=$'\033[1;33m'
NC=$'\033[0m'

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

test_patternkit ()
{
  cd "$DOCROOT_PATH"

  printf "%s\n" "${green}Testing Drupal...${NC}"
  drush en -y simpletest patternkit
  php ./core/scripts/run-tests.sh --verbose --concurrency 10 --url http://${VIRTUAL_HOST} --module patternkit
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

time -p test_patternkit

#-------------------------- END: Execution --------------------------------
