#!/usr/bin/env bash

## Test site installation
##
## Usage: fin test

# Abort if anything fails
set -euo pipefail

# Debug mode switch
if [[ "${DEBUG}" != "" ]]; then
    set -x
fi

printf "%s\n" "Testing home page..."
curl -sL -I http://${VIRTUAL_HOST} | grep "HTTP/1.1 200 OK"
curl -sL http://${VIRTUAL_HOST} | grep "My Drupal 8 Site"
printf "%s\n" "Testing login page..."
curl -sL -I http://${VIRTUAL_HOST}/user/login | grep "HTTP/1.1 200 OK"
