#!/usr/bin/env bash

## Use git-flow to start a new feature branch
##
## Usage: fin feature-start

# Abort if anything fails
set -euo pipefail

#-------------------------- Helper functions --------------------------------

# Console colors
yellow=$'\033[1;33m'
green_bg=$'\033[1;97;42m'
NC=$'\033[0m'

#-------------------------- Execution --------------------------------

## @todo For WSL2, we need to figure out how to run the following:
## printf 'DOCKSAL_HOST_IP="%s"' $(ip route list default | grep -oP '(?<=default via\s)\d+(\.\d+){3}') >> ./.docksal/docksal-local.env
## printf 'xdebug.client_host = "%s"' $(ip route list default | grep -oP '(?<=default via\s)\d+(\.\d+){3}') >> ./.docksal/etc/php/php.ini

CURRENT_XDEBUG=$(fin config get --env=local XDEBUG_ENABLED)
if [[ -z "$CURRENT_XDEBUG" ]] || [[ "$CURRENT_XDEBUG" = '"0"' ]]
 then
    printf "%s\n" "${yellow} XDEBUG Currently disabled. enabling...${NC}"
    fin config set --env=local XDEBUG_ENABLED=1
    fin p restart
    printf "%s\n" "${green_bg} XDEBUG Turned ON! ${NC} "
 else
    printf "%s\n" "${yellow} XDEBUG Currently enabled. disabling...${NC}"
    fin config set --env=local XDEBUG_ENABLED=0
    fin p restart
    printf "%s\n" "${green_bg} XDEBUG Turned OFF! ${NC} "
fi

#-------------------------- END: Execution --------------------------------
